services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Dave1234
      MYSQL_DATABASE: hive
    volumes:
      - ./db_data:/docker-entrypoint-initdb.d
    ports:
      - '3307:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  hive:
    build: .
    volumes:
      - ./:/app
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: Dave1234
      DB_DATABASE: hive

  AI:
    build:
      context: https://github.com/2themax2/itvb23ows-hive-ai
      dockerfile: Dockerfile
