services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Dave1234
      MYSQL_DATABASE: hive
    volumes:
      - ./db_data:/docker-entrypoint-initdb.d
    ports:
      - '3307:3306'
  hive:
    build: .
    volumes:
      - ./:/app
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: Dave1234
      DB_DATABASE: hive