name: PHP Composer and PHPUnit Tests

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'  # Update with your PHP version
        
    - name: Validate composer.json and composer.lock
      run: composer validate --no-check-all --strict

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run tests with phpunit
      id: phpunit
      run: ./vendor/bin/phpunit --log-junit=phpunit.xml

    - name: Display PHPUnit tests results
      uses: EnricoCi/github-action-phpunit@main
      with:
        file: phpunit.xml
      if: always()
