name: PHP Tests, Coverage, and Qodana

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  test-and-qodana:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: xdebug
          coverage: xdebug

      - name: Validate composer.json and composer.lock
        run: composer validate --no-check-all --strict

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run tests with PHPUnit and generate coverage
        run: ./vendor/bin/phpunit --coverage-clover coverage.xml

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.3
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          args: --baseline,qodana.sarif.json
          coverage-reports: coverage.xml